/** @type {import("prettier").Config} */
module.exports = {
  arrowParens: "always",
  printWidth: 80,
  singleQuote: false,
  jsxSingleQuote: false,
  semi: true,
  trailingComma: "all",
  tabWidth: 2,
  plugins: [
    require.resolve("prettier-plugin-tailwindcss"),
    require.resolve("@ianvs/prettier-plugin-sort-imports"),
  ],
  tailwindConfig: "./packages/config/tailwind",
  importOrder: [
    "^(react/(.*)$)|^(react$)|^(react-native(.*)$)",
    "^next(.*)$",
    "^@nestjs/(.*)$",
    "^(next/(.*)$)|^(next$)",
    "^(expo(.*)$)|^(expo$)",
    "<THIRD_PARTY_MODULES>",
    "^@opad/(.*)$",
    "",
    // web
    "^~/lib/(.*)$",
    "^~/hooks/(.*)$",
    "^~/contexts/(.*)$",
    "^~/env/(.*)$",
    "^~/components/(.*)$",
    "^~/stores/(.*)$",
    "^~/styles/(.*)$",

    // api
    "(.*).module$",
    "((.*)/services/(.*)|(.*).service)$",
    "((.*)/controllers/(.*)|(.*).controller)$",
    "((.*)/guards/(.*)|(.*).guard)$",
    "((.*)/decorators/(.*)|(.*).decorator)$",
    "((.*)/strategies/(.*)|(.*).strategy)$",
    "((.*)/errors/(.*)|(.*).error)$",
    "(.*)/utils/(.*)$",
    "((.*)/dto/(.*)|(.*).dto)$",
    "((.*)/types/(.*)|(.*).type)$",
    "((.*)/interfaces/(.*)|(.*).interface)$",
    
    "^~/(.*)$",
    "^[./]",
  ],
  importOrderSeparation: false,
  importOrderSortSpecifiers: true,
  importOrderBuiltinModulesToTop: true,
  importOrderParserPlugins: ["typescript", "jsx", "decorators-legacy"],
  importOrderMergeDuplicateImports: true,
  importOrderCombineTypeAndValueImports: true,
};